<template>
	<div class="text2image-picker-content-wrapper">
		<div v-if="!pickerEnabled" class="text2image-picker-content">
			<h2>
				{{ t('text2image_helper', 'ERROR: No free prompt provider available') }}
			</h2>
		</div>
		<div v-if="pickerEnabled" class="text2image-picker-content">
			<h2>
				{{ t('text2image_helper', 'AI text generation') }}
			</h2>
			<a class="attribution" target="_blank" :href="poweredByUrl">
				{{ poweredByTitle }}
			</a>
			<div class="input-wrapper">
				<NcTextField ref="text2image-search-input"
					:value.sync="query"
					:label="inputPlaceholder"
					:disabled="loading"
					:show-trailing-button="!!query"
					@keydown.enter="generate"
					@trailing-button-click="query = ''" />
			</div>
			<div v-if="results === null || query === ''" class="prompts">
				<NcUserBubble v-for="p in prompts"
					:key="p.id + p.value"
					class="prompt-bubble"
					:title="p.value"
					:size="30"
					avatar-image="icon-history"
					:display-name="p.value"
					@click="query = p.value" />
			</div>
			<div v-if="results !== null" class="preview">
				<h3>{{ t('text2image_helper', 'Preview') }}</h3>
				<!-- Loop through all results and display them in a Text2ImageDisplay -->
				<div v-for="(r, index) in results" :key="index">
					<Text2ImageDisplay :src="r.url" :prompt="r.prompt" />
				</div>
			</div>
			<div class="footer">
				<NcButton class="advanced-button"
					type="tertiary"
					:aria-label="t('text2image_helper', 'Show/hide advanced options')"
					@click="showAdvanced = !showAdvanced">
					<template #icon>
						<component :is="showAdvancedIcon" />
					</template>
					{{ t('text2image_helper', 'Advanced options') }}
				</NcButton>
				<NcButton type="secondary"
					:aria-label="t('text2image_helper', 'Preview text generation by AI')"
					:disabled="loading || !query"
					@click="generate">
					{{ previewButtonLabel }}
					<template #icon>
						<NcLoadingIcon v-if="loading" />
						<RefreshIcon v-else-if="results !== null" />
						<EyeIcon v-else />
					</template>
				</NcButton>
				<NcButton v-if="results !== null"
					type="primary"
					:aria-label="t('text2image_helper', 'Submit image generated by AI')"
					:disabled="loading || emptyResult"
					@click="submit">
					{{ t('text2image_helper', 'Send') }}
					<template #icon>
						<ArrowRightIcon />
					</template>
				</NcButton>
			</div>
			<div v-show="showAdvanced" class="advanced">
				<div class="line">
					<NcCheckboxRadioSwitch class="include-query" :checked.sync="includeQuery">
						{{ t('text2image_helper', 'Include the prompt in the result') }}
					</NcCheckboxRadioSwitch>
					<div class="spacer" />
				</div>
				<div class="line">
					<label for="nb-results">
						{{ t('text2image_helper', 'How many results to generate') }}
					</label>
					<div class="spacer" />
					<input id="nb-results"
						v-model="completionNumber"
						type="number"
						min="1"
						max="10"
						step="1">
				</div>
			</div>
		</div>
	</div>
</template>

<script>
import EyeIcon from 'vue-material-design-icons/Eye.vue'
import RefreshIcon from 'vue-material-design-icons/Refresh.vue'
import ArrowRightIcon from 'vue-material-design-icons/ArrowRight.vue'
import ChevronRightIcon from 'vue-material-design-icons/ChevronRight.vue'
import ChevronDownIcon from 'vue-material-design-icons/ChevronDown.vue'
import HelpCircleIcon from 'vue-material-design-icons/HelpCircle.vue'

import NcButton from '@nextcloud/vue/dist/Components/NcButton.js'
import NcLoadingIcon from '@nextcloud/vue/dist/Components/NcLoadingIcon.js'
import NcTextField from '@nextcloud/vue/dist/Components/NcTextField.js'
import NcSelect from '@nextcloud/vue/dist/Components/NcSelect.js'
import NcCheckboxRadioSwitch from '@nextcloud/vue/dist/Components/NcCheckboxRadioSwitch.js'
import NcUserBubble from '@nextcloud/vue/dist/Components/NcUserBubble.js'
import NcRichContenteditable from '@nextcloud/vue/dist/Components/NcRichContenteditable.js'

import axios from '@nextcloud/axios'
import { generateUrl } from '@nextcloud/router'
import { showError } from '@nextcloud/dialogs'

import Text2ImageDisplay from '../Components/Text2ImageDisplay.vue'

export default {
	name: 'Text2ImageHelperCustomPickerElement',

	components: {
		NcButton,
		NcLoadingIcon,
		NcTextField,
		NcSelect,
		NcCheckboxRadioSwitch,
		ChevronRightIcon,
		ChevronDownIcon,
		HelpCircleIcon,
		ArrowRightIcon,
		NcUserBubble,
		RefreshIcon,
		EyeIcon,
		NcRichContenteditable,
		Text2ImageDisplay,
	},

	props: {
		providerId: {
			type: String,
			required: true,
		},
		accessible: {
			type: Boolean,
			default: false,
		},
		pickerEnabled: {
			type: Boolean,
			default: true,
		},
	},

	data() {
		return {
			query: '',
			results: null,
			loading: false,
			models: [],
			inputPlaceholder: t('text2image_helper', 'A hedgehog laid back on a couch'),
			showAdvanced: false,
			includeQuery: false,
			completionNumber: 1,
			prompts: null,
		}
	},

	computed: {
		showAdvancedIcon() {
			return this.showAdvanced
				? ChevronDownIcon
				: ChevronRightIcon
		},
		previewButtonLabel() {
			return this.results !== null
				? t('text2image_helper', 'Regenerate')
				: t('text2image_helper', 'Preview')
		},
		emptyResult() {
			return this.results === null || this.results.length === 0
		},
	},

	watch: {
	},

	mounted() {
		this.focusOnInput()
		this.getPromptHistory()
	},

	methods: {
		focusOnInput() {
			setTimeout(() => {
				this.$refs['text2image-search-input'].$el.getElementsByTagName('input')[0]?.focus()
			}, 300)
		},
		getPromptHistory() {
			const params = {
				params: {
				},
			}
			const url = generateUrl('/apps/text2image_helper/prompt_history')
			return axios.get(url, params)
				.then((response) => {
					this.prompts = response.data
				})
				.catch((error) => {
					console.error(error)
				})
		},
		submit() {
			// Get all urls in the results and emit them as one string
			const emitString = this.results.map(r => r.url).join('\n')
			this.$emit('submit', emitString.trim())
		},
		insertPrompt(prompt) {
			if (this.prompts.find(p => p.value === prompt) === undefined) {
				this.prompts.unshift({
					id: 0,
					value: prompt,
				})
			}
		},
		generate() {
			if (this.query === '') {
				return
			}
			this.loading = true
			const params = {
				prompt: this.query,
				nResults: this.completionNumber,
			}
			const url = generateUrl('/apps/text2image_helper/process_prompt')
			return axios.post(url, params)
				.then((response) => {
					const data = response.data
					if (data.length && data.length > 0) {
						this.processCompletion(data)
						this.insertPrompt(this.query)
					} else {
						this.error = response.data.error
					}
				})
				.catch((error) => {
					console.error('Image generation request error', error)
					showError(
						t('text2image_helper', 'Image generation error') + ': '
						+ (error.response?.data?.body?.error?.message
							|| error.response?.data?.body?.error?.code
							|| error.response?.data?.error
							|| t('text2image_helper', 'Unknown image generation error')
						),
					)
				})
				.then(() => {
					this.loading = false
				})
		},
		processCompletion(response) {
			this.results = response.filter(c => !!c.url && !!c.prompt).map(c => ({ url: c.url.replace(/^\s+|\s+$/g, ''), prompt: c.prompt.replace(/^\s+|\s+$/g, '') }))
			if (this.results.length === 0) {
				this.results = null
			}
		},
	},
}
</script>

<style scoped lang="scss">
.text2image-picker-content-wrapper {
	width: 100%;
}

.text2image-picker-content {
	display: flex;
	flex-direction: column;
	align-items: center;
	justify-content: center;
	padding: 12px 16px 16px 16px;

	h2 {
		display: flex;
		align-items: center;
	}

	.prompts {
		margin-top: 8px;
		display: flex;
		flex-wrap: wrap;
		align-items: center;

		>* {
			margin-right: 8px;
		}
	}

	.prompt-bubble {
		max-width: 250px;
	}

	.preview {
		width: 100%;

		h3 {
			font-weight: bold;
		}

		.editable-preview {
			width: 100% !important;
			max-height: 300px !important;
		}
	}

	.spacer {
		flex-grow: 1;
	}
	.input-wrapper {
		display: flex;
		align-items: center;
		width: 100%;
	}

	.prompt-select {
		width: 100%;
		margin-top: 4px;
	}

	.footer {
		width: 100%;
		display: flex;
		align-items: center;
		justify-content: end;
		margin-top: 12px;

		>* {
			margin-left: 4px;
		}
	}

	.advanced {
		width: 100%;
		padding: 12px 0;

		.line {
			display: flex;
			align-items: center;
			margin-top: 8px;

			input {
				width: 200px;
			}
		}

		input[type=number] {
			width: 120px;
			appearance: initial !important;
			-moz-appearance: initial !important;
			-webkit-appearance: initial !important;
		}

		.include-query {
			margin-right: 16px;
		}
	}
}
</style>
