<template>
	<div class="text2image-picker-content-wrapper">
		<div v-if="!pickerEnabled" class="text2image-picker-content">
			<h2>
				{{ t('text2image_helper', 'ERROR: No image generation provider available') }}
			</h2>
		</div>
		<div v-if="pickerEnabled" class="text2image-picker-content">
			<h2>
				{{ t('text2image_helper', 'AI Image Generation') }}
			</h2>
			<div class="input-wrapper">
				<NcTextField ref="text2image-search-input"
					:value.sync="query"
					:label="inputPlaceholder"
					:disabled="loading"
					:show-trailing-button="!!query"
					@keydown.enter="generate"
					@trailing-button-click="query = ''" />
			</div>
			<div v-if="result === null || query === ''" class="prompts">
				<NcUserBubble v-for="p in prompts"
					:key="p.id + p.value"
					class="prompt-bubble"
					:title="p.value"
					:size="30"
					avatar-image="icon-history"
					:display-name="p.value"
					@click="query = p.value" />
			</div>
			<div v-if="result !== null" class="preview-container">
				<h3>{{ t('text2image_helper', 'Preview') }}</h3>
				<div class="image-preview">
					<Text2ImageDisplay :src="result.url" :prompt="result.prompt" />
				</div>
			</div>
			<div class="footer">
				<div class="line">
					<NcCheckboxRadioSwitch class="include-query"
						:checked.sync="displayPrompt">
						{{ t('text2image_helper', 'Include the prompt in the result') }}
					</NcCheckboxRadioSwitch>
					<div class="spacer" />
				</div>
				<NcButton type="secondary"
					:aria-label="t('text2image_helper', 'Preview image generation by AI')"
					:disabled="loading || !query"
					@click="generate">
					{{ previewButtonLabel }}
					<template #icon>
						<NcLoadingIcon v-if="loading" />
						<RefreshIcon v-else-if="result !== null" />
						<EyeIcon v-else />
					</template>
				</NcButton>
				<NcButton v-if="result !== null"
					type="primary"
					:aria-label="t('text2image_helper', 'Submit image generated by AI')"
					:disabled="loading || emptyResult"
					@click="submit">
					{{ t('text2image_helper', 'Send') }}
					<template #icon>
						<ArrowRightIcon />
					</template>
				</NcButton>
			</div>
		</div>
	</div>
</template>

<script>
import EyeIcon from 'vue-material-design-icons/Eye.vue'
import RefreshIcon from 'vue-material-design-icons/Refresh.vue'
import ArrowRightIcon from 'vue-material-design-icons/ArrowRight.vue'

import NcButton from '@nextcloud/vue/dist/Components/NcButton.js'
import NcLoadingIcon from '@nextcloud/vue/dist/Components/NcLoadingIcon.js'
import NcTextField from '@nextcloud/vue/dist/Components/NcTextField.js'
import NcCheckboxRadioSwitch from '@nextcloud/vue/dist/Components/NcCheckboxRadioSwitch.js'
import NcUserBubble from '@nextcloud/vue/dist/Components/NcUserBubble.js'

import axios from '@nextcloud/axios'
import { generateUrl } from '@nextcloud/router'
import { showError } from '@nextcloud/dialogs'

import Text2ImageDisplay from '../Components/Text2ImageDisplay.vue'

export default {
	name: 'Text2ImageHelperCustomPickerElement',

	components: {
		NcButton,
		NcLoadingIcon,
		NcTextField,
		NcCheckboxRadioSwitch,
		ArrowRightIcon,
		NcUserBubble,
		RefreshIcon,
		EyeIcon,
		Text2ImageDisplay,
	},

	props: {
		providerId: {
			type: String,
			required: true,
		},
		accessible: {
			type: Boolean,
			default: false,
		},
		pickerEnabled: {
			type: Boolean,
			default: true,
		},
	},

	data() {
		return {
			query: '',
			result: null,
			loading: false,
			models: [],
			inputPlaceholder: t('text2image_helper', 'A hedgehog laid back on a couch'),
			displayPrompt: true,
			completionNumber: 1,
			prompts: null,
			submitted: false,
		}
	},

	computed: {
		previewButtonLabel() {
			return this.result !== null
				? t('text2image_helper', 'Regenerate')
				: t('text2image_helper', 'Preview')
		},
		emptyResult() {
			return this.result === null || this.result.length === 0
		},
	},

	watch: {
		displayPrompt(newValue) {
			localStorage.setItem('text2image_display_prompt', JSON.stringify(newValue))
		},
	},

	mounted() {
		this.focusOnInput()
		this.getPromptHistory()
		const cachedValue = localStorage.getItem('text2image_display_prompt') === 'true'
		if (cachedValue !== null) {
			this.displayPrompt = cachedValue
		}
	},

	beforeDestroy() {
		if (!this.submitted) {
			this.cancelGenerations()
		}
	},

	methods: {
		focusOnInput() {
			setTimeout(() => {
				this.$refs['text2image-search-input'].$el.getElementsByTagName('input')[0]?.focus()
			}, 300)
		},
		getPromptHistory() {
			const params = {
				params: {
				},
			}
			const url = generateUrl('/apps/text2image_helper/prompt_history')
			return axios.get(url, params)
				.then((response) => {
					this.prompts = response.data
				})
				.catch((error) => {
					console.error(error)
				})
		},
		submit() {
			this.submitted = true
			this.$emit('submit', this.result.url)
		},
		insertPrompt(prompt) {
			if (this.prompts.find(p => p.value === prompt) === undefined) {
				this.prompts.unshift({
					id: 0,
					value: prompt,
				})
			}
		},
		cancelGeneration() {
			const url = generateUrl('/apps/text2image_helper/cancel_generation')
			axios.post(url, { imageId: this.result.image_id })
				.catch((error) => {
					console.error('Image generation cancel request error', error)
					showError(
						t('text2image_helper', 'Image generation cancel error') + ': '
						+ (error.response?.data?.body?.error?.message
							|| error.response?.data?.body?.error?.code
							|| error.response?.data?.error
							|| t('text2image_helper', 'Unknown image generation cancel error')
						),
					)
				})
		},
		generate() {

			if (this.result !== null) {
				this.cancelGeneration()
			}

			if (this.query === '') {
				return
			}
			this.loading = true
			const params = {
				prompt: this.query,
				nResults: this.completionNumber,
				displayPrompt: this.displayPrompt,
			}
			const url = generateUrl('/apps/text2image_helper/process_prompt')
			return axios.post(url, params)
				.then((response) => {
					const data = response.data
					if (data?.url !== undefined) {
						this.result = data
						this.insertPrompt(this.query)
					} else {
						showError(t('text2image_helper', 'Unexpected response from server.'))
					}
				})
				.catch((error) => {
					console.error('Image generation request error', error)
					showError(
						t('text2image_helper', 'Image generation error') + ': '
						+ (error.response?.data?.body?.error?.message
							|| error.response?.data?.body?.error?.code
							|| error.response?.data?.error
							|| t('text2image_helper', 'Unknown image generation error')
						),
					)
				})
				.then(() => {
					this.loading = false
				})
		},
	},
}
</script>

<style scoped lang="scss">
.text2image-picker-content-wrapper {
	width: 100%;
}

.text2image-picker-content {
	display: flex;
	flex-direction: column;
	align-items: center;
	justify-content: center;
	padding: 12px 16px 16px 16px;

	h2 {
		display: flex;
		align-items: center;
	}

	.prompts {
		margin-top: 8px;
		display: flex;
		flex-wrap: wrap;
		align-items: center;

		>* {
			margin-right: 8px;
		}
	}

	.prompt-bubble {
		max-width: 250px;
	}

	.preview-container {
		width: 100%;

		.image-preview {
			margin-top: 8px;
			border: 3px solid var(--color-border);
			border-radius: var(--border-radius-large);
			padding: 12px;
		}
	}

	.spacer {
		flex-grow: 1;
	}
	.input-wrapper {
		display: flex;
		align-items: center;
		width: 100%;
	}

	.prompt-select {
		width: 100%;
		margin-top: 4px;
	}

	.footer {
		width: 100%;
		display: flex;
		flex-direction: row;
		margin-top: 12px;
		justify-content: space-between;

		.buttons {
			width: 100%;
			display: flex;
			align-items: center;

			>* {
				margin-left: 4px;
			}
		}
	}
}
</style>
